/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Color;
import java.awt.Image;
import java.awt.Label;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import yahtzeeClient.Client;

/**
 *
 * @author PC
 */
public class Game extends javax.swing.JFrame {
    
    public Score score = new Score();
    public static Game ThisGame;
    public int turns = 0;
    public int[] myDesk = new int [5];
    public int[] rivalDesk = new int [5];
    public int rollCount = 0;
    int[] diceValues = new int [5];
    
    public void changeIcon(JLabel die,JLabel pick,JLabel emptyLbl){
        if(!isLabelEmpty(die)){
            pick.setIcon(die.getIcon());
            die.setIcon(emptyLbl.getIcon());
        }
    }
    public boolean isLabelEmpty(JLabel die){
        String urlLabel=die.getIcon().toString();
        String imageNameLabel = urlLabel.substring(urlLabel.lastIndexOf( "/" )+1, urlLabel.length()) ;
        return imageNameLabel.equals("white.png");
    }
    public void setImages(JLabel die){
        int diceNum = Integer.parseInt((die.getText().substring(die.getText().length()-1)));
         if(!isLabelEmpty(die)){
            die.setIcon(icons[diceValues[diceNum-1]]);
        }
    }
    public void setPlayerDeskImages(JLabel die,int[] desk){
        int diceNum = Integer.parseInt((die.getText().substring(die.getText().length()-1)));
         if(!isLabelEmpty(die)){
            die.setIcon(icons[desk[diceNum-1]]);
        }
    }
    ImageIcon icons[];
    Random rand;
    /**
     * Creates new form clientGame
     */
    @SuppressWarnings("empty-statement")
    public Game() {
       initComponents();
       ThisGame = this;
              
     
            icons = new ImageIcon[7];

              icons[0] = new javax.swing.ImageIcon(getClass().getResource("/game/images/die1.png"));
              icons[1] = new javax.swing.ImageIcon(getClass().getResource("/game/images/die2.png"));
              icons[2] = new javax.swing.ImageIcon(getClass().getResource("/game/images/die3.png"));
              icons[3] = new javax.swing.ImageIcon(getClass().getResource("/game/images/die4.png"));
              icons[4] = new javax.swing.ImageIcon(getClass().getResource("/game/images/die5.png"));
              icons[5] = new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"));
              icons[6] = new javax.swing.ImageIcon(getClass().getResource("/game/images/turn.png"));
        lbl_die1.setIcon(icons[0]);
        lbl_die2.setIcon(icons[1]);
        lbl_die3.setIcon(icons[2]);
        lbl_die4.setIcon(icons[3]);
        lbl_die5.setIcon(icons[4]);
        
        lbl_oppDie1.setIcon(icons[6]);
        lbl_oppDie2.setIcon(icons[6]);
        lbl_oppDie3.setIcon(icons[6]);
        lbl_oppDie4.setIcon(icons[6]);
        lbl_oppDie5.setIcon(icons[6]);
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_die1 = new javax.swing.JLabel();
        lbl_die2 = new javax.swing.JLabel();
        lbl_die3 = new javax.swing.JLabel();
        lbl_die4 = new javax.swing.JLabel();
        lbl_die5 = new javax.swing.JLabel();
        lbl_pick1 = new javax.swing.JLabel();
        lbl_pick2 = new javax.swing.JLabel();
        lbl_pick3 = new javax.swing.JLabel();
        lbl_pick4 = new javax.swing.JLabel();
        lbl_pick5 = new javax.swing.JLabel();
        lbl_oppDie1 = new javax.swing.JLabel();
        lbl_oppDie2 = new javax.swing.JLabel();
        lbl_oppDie3 = new javax.swing.JLabel();
        lbl_oppDie4 = new javax.swing.JLabel();
        lbl_oppDie5 = new javax.swing.JLabel();
        lbl_oppPick1 = new javax.swing.JLabel();
        lbl_oppPick2 = new javax.swing.JLabel();
        lbl_oppPick3 = new javax.swing.JLabel();
        lbl_oppPick4 = new javax.swing.JLabel();
        lbl_oppPick5 = new javax.swing.JLabel();
        btn_roll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl_fullHouse = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbl_threeOfaKind = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl_fourOfaKindScore1 = new javax.swing.JLabel();
        lbl_threeOfaKindScore1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lbl_largeStraightScore1 = new javax.swing.JLabel();
        lbl_smallStraightScore1 = new javax.swing.JLabel();
        lbl_fullHouseScore1 = new javax.swing.JLabel();
        lbl_yahtzeeScore1 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        txt_rival_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_die1.setText("jLabel1");
        lbl_die1.setPreferredSize(new java.awt.Dimension(50, 50));
        lbl_die1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_die1MouseClicked(evt);
            }
        });

        lbl_die2.setText("jLabel2");
        lbl_die2.setPreferredSize(new java.awt.Dimension(50, 50));
        lbl_die2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_die2MouseClicked(evt);
            }
        });

        lbl_die3.setText("jLabel3");
        lbl_die3.setPreferredSize(new java.awt.Dimension(50, 50));
        lbl_die3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_die3MouseClicked(evt);
            }
        });

        lbl_die4.setText("jLabel4");
        lbl_die4.setPreferredSize(new java.awt.Dimension(50, 50));
        lbl_die4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_die4MouseClicked(evt);
            }
        });

        lbl_die5.setText("jLabel5");
        lbl_die5.setPreferredSize(new java.awt.Dimension(50, 50));
        lbl_die5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_die5MouseClicked(evt);
            }
        });

        lbl_pick1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N
        lbl_pick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pick1MouseClicked(evt);
            }
        });

        lbl_pick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N
        lbl_pick2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pick2MouseClicked(evt);
            }
        });

        lbl_pick3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N
        lbl_pick3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pick3MouseClicked(evt);
            }
        });

        lbl_pick4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N
        lbl_pick4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pick4MouseClicked(evt);
            }
        });

        lbl_pick5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N
        lbl_pick5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pick5MouseClicked(evt);
            }
        });

        lbl_oppDie1.setText("jLabelOpp1");

        lbl_oppDie2.setText("jLabelOpp2");

        lbl_oppDie3.setText("jLabelOpp3");

        lbl_oppDie4.setText("jLabelOpp4");

        lbl_oppDie5.setText("jLabelOpp5");

        lbl_oppPick1.setBackground(new java.awt.Color(100, 255, 255));
        lbl_oppPick1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_oppPick1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N

        lbl_oppPick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N

        lbl_oppPick3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N

        lbl_oppPick4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N

        lbl_oppPick5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/white.png"))); // NOI18N

        btn_roll.setText("Roll Dice");
        btn_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rollActionPerformed(evt);
            }
        });

        jLabel1.setText("Ones:");

        jLabel2.setText("Twos:");

        jLabel3.setText("Threes:");

        jLabel4.setText("Fours:");

        jLabel7.setText("Fives:");

        jLabel8.setText("Sixes:");

        jLabel9.setText("Sum:");

        jLabel10.setText("Bonus:");

        jLabel26.setText("Total Score:");

        jLabel27.setText("Yahtzee:");

        jLabel28.setText("Chance:");

        jLabel29.setText("Large Straight:");

        jLabel30.setText("Small Straight:");

        lbl_fullHouse.setText("Full House:");

        jLabel32.setText("Four of a kind:");

        lbl_threeOfaKind.setText("Three of a kind:");

        jLabel34.setText("0");

        jLabel35.setText("   You");

        jLabel36.setText("Opponent");

        jLabel37.setText("0");

        jLabel38.setText("0");

        jLabel39.setText("0");

        jLabel40.setText("0");

        lbl_fourOfaKindScore1.setText("0");

        lbl_threeOfaKindScore1.setText("0");

        jLabel43.setText("0");

        jLabel44.setText("0");

        jLabel45.setText("0");

        jLabel46.setText("0");

        lbl_largeStraightScore1.setText("0");

        lbl_smallStraightScore1.setText("0");

        lbl_fullHouseScore1.setText("0");

        lbl_yahtzeeScore1.setText("0");

        jLabel51.setText("0");

        jLabel52.setText("0");

        jLabel53.setText("0");

        jLabel54.setText("0");

        jLabel55.setText("0");

        jLabel56.setText("0");

        jLabel57.setText("0");

        jLabel58.setText("0");

        jLabel59.setText("0");

        jLabel60.setText("0");

        jLabel61.setText("0");

        jLabel62.setText("0");

        jLabel63.setText("0");

        jLabel64.setText("0");

        jLabel65.setText("0");

        jLabel66.setText("0");

        jLabel67.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel32)
                            .addComponent(lbl_fullHouse))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jLabel36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel43)
                                    .addComponent(lbl_threeOfaKindScore1)
                                    .addComponent(lbl_fourOfaKindScore1)
                                    .addComponent(lbl_fullHouseScore1)
                                    .addComponent(lbl_smallStraightScore1)
                                    .addComponent(lbl_largeStraightScore1)
                                    .addComponent(jLabel46)
                                    .addComponent(lbl_yahtzeeScore1)
                                    .addComponent(jLabel51))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel54)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel60)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel65)
                                    .addComponent(jLabel64)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel66)
                                    .addComponent(jLabel67))
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(lbl_threeOfaKind))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_threeOfaKind)
                            .addComponent(lbl_threeOfaKindScore1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(lbl_fourOfaKindScore1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fullHouse)
                            .addComponent(lbl_fullHouseScore1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(lbl_smallStraightScore1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(lbl_largeStraightScore1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(lbl_yahtzeeScore1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel62)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel66)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel51)
                    .addComponent(jLabel67))
                .addContainerGap())
        );

        jLabel5.setText("Score Table");

        txt_name.setText("Name");

        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });

        txt_rival_name.setText("Rival Name");
        txt_rival_name.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_die1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_die2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_die3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_die4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_die5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_roll)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_pick1)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_pick2)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_pick3)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_pick4)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_pick5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_connect))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_oppDie1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_oppDie2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_oppDie3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_oppPick1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_oppPick2))
                                    .addComponent(txt_rival_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_oppPick3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_oppDie4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_oppDie5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_oppPick4)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(lbl_oppPick5)))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txt_rival_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_oppPick1)
                            .addComponent(lbl_oppPick3)
                            .addComponent(lbl_oppPick2)
                            .addComponent(lbl_oppPick5)
                            .addComponent(lbl_oppPick4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_oppDie1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_oppDie3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_oppDie5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_oppDie4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_oppDie2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_die1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_die3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_die2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_die5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_die4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_pick1)
                            .addComponent(lbl_pick3)
                            .addComponent(lbl_pick5)
                            .addComponent(lbl_pick4)
                            .addComponent(lbl_pick2))
                        .addGap(18, 18, 18)
                        .addComponent(btn_roll))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_connect))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_die1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_die1MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_die1,lbl_pick1,lbl_oppPick1);
    }//GEN-LAST:event_lbl_die1MouseClicked

    private void btn_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rollActionPerformed
        // TODO add your handling code here:
      
        rollCount++;
        for(int i=0;i<5;i++){
            diceValues[i]=(int)(Math.random()*5);
        }
        setImages(lbl_die1);
        setImages(lbl_die2);
        setImages(lbl_die3);
        setImages(lbl_die4);
        setImages(lbl_die5);
        
        myDesk = diceValues;
        
        String hand = score.getHand(myDesk);
        
        switch(hand){
        
            case "fullHouse":
                lbl_fullHouseScore1.setForeground(Color.red);
                lbl_fullHouseScore1.setText(Integer.toString(score.score));
                break;
            case "threeOfaKind":
                lbl_threeOfaKindScore1.setForeground(Color.red);
                lbl_threeOfaKindScore1.setText(Integer.toString(score.score));
                break;
            case "fourOfaKind":
                lbl_fourOfaKindScore1.setForeground(Color.red);
                lbl_fourOfaKindScore1.setText(Integer.toString(score.score));
                break;
            case "yahtzee":
                lbl_yahtzeeScore1.setForeground(Color.red);
                lbl_yahtzeeScore1.setText(Integer.toString(score.score));
                break;
            case "straight":
                lbl_largeStraightScore1.setForeground(Color.red);
                lbl_largeStraightScore1.setText(Integer.toString(score.score));
                break;
            case "smallStraight":
                lbl_smallStraightScore1.setForeground(Color.red);
                lbl_smallStraightScore1.setText(Integer.toString(score.score));
                break;
        }

        myDesk = diceValues;
        Message msg = new Message(Message.Message_Type.Selected);
        msg.content = myDesk;
        Client.Send(msg);
//        setPlayerDeskImages(lbl_oppDie1, rivalDesk);
//        setPlayerDeskImages(lbl_oppDie2, rivalDesk);
//        setPlayerDeskImages(lbl_oppDie3, rivalDesk);
//        setPlayerDeskImages(lbl_oppDie4, rivalDesk);
//        setPlayerDeskImages(lbl_oppDie5, rivalDesk);
        if(rollCount==3){
            btn_roll.setEnabled(false);
        }
    }//GEN-LAST:event_btn_rollActionPerformed

    private void lbl_die2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_die2MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_die2,lbl_pick2,lbl_oppPick1);
    }//GEN-LAST:event_lbl_die2MouseClicked

    private void lbl_die3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_die3MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_die3,lbl_pick3,lbl_oppPick1);
    }//GEN-LAST:event_lbl_die3MouseClicked

    private void lbl_die4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_die4MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_die4,lbl_pick4,lbl_oppPick1);
    }//GEN-LAST:event_lbl_die4MouseClicked

    private void lbl_die5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_die5MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_die5,lbl_pick5,lbl_oppPick1);
    }//GEN-LAST:event_lbl_die5MouseClicked

    private void lbl_pick1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pick1MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_pick1,lbl_die1,lbl_oppPick1);
    }//GEN-LAST:event_lbl_pick1MouseClicked

    private void lbl_pick2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pick2MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_pick2,lbl_die2,lbl_oppPick1);
    }//GEN-LAST:event_lbl_pick2MouseClicked

    private void lbl_pick3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pick3MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_pick3,lbl_die3,lbl_oppPick1);
    }//GEN-LAST:event_lbl_pick3MouseClicked

    private void lbl_pick4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pick4MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_pick4,lbl_die4,lbl_oppPick1);
    }//GEN-LAST:event_lbl_pick4MouseClicked

    private void lbl_pick5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pick5MouseClicked
        // TODO add your handling code here:
        changeIcon(lbl_pick5,lbl_die5,lbl_oppPick1);
    }//GEN-LAST:event_lbl_pick5MouseClicked

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        // TODO add your handling code here:
        //bağlanılacak server ve portu veriyoruz
        Client.Start("127.0.0.1", 2000);
        //başlangıç durumları
//        lbl_oppDie1.setIcon(icons[0]);
//        lbl_oppDie2.setIcon(icons[1]);
//        lbl_oppDie3.setIcon(icons[2]);
//        lbl_oppDie4.setIcon(icons[3]);
//        lbl_oppDie5.setIcon(icons[4]);
        btn_connect.setEnabled(false);
        txt_name.setEnabled(false);
   //     btn_pick.setEnabled(false);
    }//GEN-LAST:event_btn_connectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connect;
    private javax.swing.JButton btn_roll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_die1;
    private javax.swing.JLabel lbl_die2;
    private javax.swing.JLabel lbl_die3;
    private javax.swing.JLabel lbl_die4;
    private javax.swing.JLabel lbl_die5;
    private javax.swing.JLabel lbl_fourOfaKindScore1;
    private javax.swing.JLabel lbl_fullHouse;
    private javax.swing.JLabel lbl_fullHouseScore1;
    private javax.swing.JLabel lbl_largeStraightScore1;
    private javax.swing.JLabel lbl_oppDie1;
    private javax.swing.JLabel lbl_oppDie2;
    private javax.swing.JLabel lbl_oppDie3;
    private javax.swing.JLabel lbl_oppDie4;
    private javax.swing.JLabel lbl_oppDie5;
    private javax.swing.JLabel lbl_oppPick1;
    private javax.swing.JLabel lbl_oppPick2;
    private javax.swing.JLabel lbl_oppPick3;
    private javax.swing.JLabel lbl_oppPick4;
    private javax.swing.JLabel lbl_oppPick5;
    private javax.swing.JLabel lbl_pick1;
    private javax.swing.JLabel lbl_pick2;
    private javax.swing.JLabel lbl_pick3;
    private javax.swing.JLabel lbl_pick4;
    private javax.swing.JLabel lbl_pick5;
    private javax.swing.JLabel lbl_smallStraightScore1;
    private javax.swing.JLabel lbl_threeOfaKind;
    private javax.swing.JLabel lbl_threeOfaKindScore1;
    private javax.swing.JLabel lbl_yahtzeeScore1;
    public javax.swing.JTextField txt_name;
    public javax.swing.JTextField txt_rival_name;
    // End of variables declaration//GEN-END:variables
}
